pipeline {
    agent any

    environment {
        GIT_COMMIT = sh(returnStdout: true, script: 'git ls-remote https://github.com/rero/rerodoc-data.git refs/heads/master | cut -c1-10 ').trim()
    }

    stages {
        stage('Get Dockerfile') {
            steps {
                sh "curl -O https://raw.githubusercontent.com/rero/rerodoc-data/master/development/continuous_integration/Dockerfile"
                sh "curl -O https://raw.githubusercontent.com/rero/rerodoc-data/master/development/continuous_integration/build_app.sh"
            }
        }
        stage('Build Test Docker Image') {
                steps {
                    println('Building GIT_COMMIT:'+GIT_COMMIT+ ' ...')
                    script {
                        app_dev = docker.build('rero/rerodoc-data:test', '--build-arg GIT_COMMIT=$GIT_COMMIT --rm  -f Dockerfile .')
                    }
                }
        }
        stage('Run Test') {
            steps {
                script {
                   sh "docker run --rm rero/rerodoc-data:test"
                }
            }
        }
        stage('Cleaning') {
                steps {
                    echo 'Cleaning....'
                    script {
                        sh "docker rmi rero/rerodoc-data:test"
                    }
                }
         }
    }
    post {
        failure {
            echo 'failure: dying now'
            mail (to: 'software@rero.ch',
                  subject: "[Jenkins] Job '${env.JOB_NAME}' (${env.BUILD_NUMBER}) has failed",
                  body: "Please go to ${env.BUILD_URL}.");
            script {
                sh "docker rmi rero/rerodoc-data:test"
            }
        }
    }
}
